### PR TITLE
Vertical auto resize

### PR DESCRIPTION
**Pull request by ftp27**
It is needed to put AloeStackView on a ViewController centre without height issues.

### CODE REVIEW

**Comment by ftp27** [comment]
image

For example

**Comment by ftp27** [comment]
@marlimox I had an issue with positing AloeStackView in centre of the screen with height dynamically changing with subviews heights. I fixed it with finding stackView subview and changing constraints for it. This commit helps to do the same but without hacks

**Comment by JUSTINMKAUFMAN** [comment]
This is useful for some of our views, thanks for the contribution.

**Comment by ftp27** [comment]
@JUSTINMKAUFMAN Tests are failed after merge. It seems like that is the Travis issue.

**Comment by apang42** [comment]
Hey @ftp27 , for this use case, does it require scrolling? If not, it would probably be better to just use a `UIStackView` directly for this use case

**Comment by ftp27** [comment]
@apang42 this issue is 7 months old. I don't remember what about it and I don't care anymore.

**Pull request closed without merging**
