### PR TITLE
Change alpha value of separatorView according to isHidden state of StackViewCell

### PR DESCRIPTION
**Pull request by ParkGwangBeom**
Separated isHidden job from # 7.

### CODE REVIEW

**Comment by ParkGwangBeom** [comment]
In the Before screen, you can see that the seperator lines of the label views below overlap when you turn off the switch.

### Before
before

### After
after

**Comment by marlimox** [comment]
@ParkGwangBeom you’ll need to rebase this PR before merging

**Comment by ParkGwangBeom** [comment]
@marlimox  If you do not mind, can you close this pr and make a new pr and upload it?

**Comment by marlimox** [comment]
Hi @ParkGwangBeom I wish I could but unfortunately I don’t have access to a computer at the moment! I’ll only have access via my phone for the next several days. That’s why I’ve been slow responding to your other PR, sorry about that!

 I can try to rebase and merge through the GirHub interface, I’ll see how that goes.

**Pull request merged**
